# Generated by Django 5.2.6 on 2025-12-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Системное имя тега')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Читабельное имя тега')),
            ],
        ),
    ]
