# Generated by Django 5.2.6 on 2025-12-18 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_document_recognized_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='education_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Курс обучения'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание/Комментарии')),
                ('file', models.FileField(blank=True, null=True, upload_to='achievements/', verbose_name='Файл подтверждения')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('users', models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
        ),
    ]
