# Generated by Django 5.2.6 on 2025-12-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_studentprofile_education_year_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='tags.tag', verbose_name='Теги'),
        ),
    ]
